Feature/ui page installer
ExFace/ModxCmsConnector pull request #13
Opened 2017-11-09 17:44 UTC by stevi84

2017-11-13 16:00 UTC, stevi84 commented
Duplizieren von Seiten, Vererben von Templates, Verschieben von Seiten wurde angepasst.

2017-11-14 08:59 UTC, kabachello requested changes

2017-11-14 08:59 UTC, kabachello commented on CmsConnectors/Modx.php
> +    protected function createPageFromModx()
Libere "createPageFromApi" um von CreatePageFromDb zu unterscheiden (ist ja beides MODx)

2017-11-14 13:21 UTC, stevi84 commented
Ich habe die entsprechenden Sachen angepasst.

2017-11-14 16:41 UTC, kabachello approved these changes

2017-11-14 16:42 UTC, merged